"""
Django settings for Dreamstream project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t744n!j*k=w2$l2=v6o3fgqp7ue=#ufru)cz(!g*m@t*_j1$!i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    "commons",
    "accounts",
    "dreams",
    "form_manager",
    "ithelps",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "django_comment_migrate",
    "guardian",
]

INSTALLED_APPS = DEFAULT_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Dreamstream.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'Dreamstream.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.menus',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dreamstream.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # 連線postgresql
        "NAME": "dreamstream",
        "USER": "dreamstream",
        "PASSWORD": "LLC123abc@",
        "HOST": "10.20.200.90",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

if sys.platform == "linux":
    STATIC_ROOT = os.path.join(BASE_DIR, "static/")
else:
    STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
FONTS_DIRS = os.path.join(BASE_DIR, "static", "fonts")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Specifying authentication backends
AUTHENTICATION_BACKENDS = [
    "accounts.backend.CustomAuthBackend",
    "guardian.backends.ObjectPermissionBackend",
]

# Logger Settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "simple": {"format": "%(levelname)s %(message)s"},
        # 彩色 formatter（僅在 DEBUG 使用）
        "color": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d%(reset)s %(message)s",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
            "style": "%",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            # 注意：使用 dictConfig 支援的 ext:// 指定 stdout；或省略使用預設
            "stream": "ext://sys.stdout",
            "formatter": "verbose",  # 預設非彩色
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

if DEBUG:
    LOGGING["handlers"]["console"]["formatter"] = "color"
    LOGGING["loggers"]["django.db.backends"] = {
        "handlers": ["console"],
        "level": "WARNING",
        "propagate": False,
    }

# Default page
LOGIN_REDIRECT_URL = "/"

# SMTP CONFIGURATION
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "alex.yang@breadoflife.taipei"
EMAIL_HOST_PASSWORD = "ptutgpaamhcavxkm"
DEFAULT_FROM_EMAIL = "no-reply@breadoflife.taipei"
DEFAULT_FROM_NAME = "台北靈糧堂"

# SESSION
SESSION_COOKIE_AGE = 60 * 60 * 3
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = True

# CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://dreamstream.bolcc.taipei",
    "https://8585.bolcc.taipei",
]
CSRF_COOKIE_SECURE = True

# 告訴 Django 上傳的檔案要存放在硬碟的哪個資料夾
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 網頁存取圖片時的網址前綴 (例如: /media/ithelp-files/abc.jpg)
MEDIA_URL = '/media/'


# GOOGLE_RECAPTCHA
GOOGLE_RECAPTCHA_ENTERPRISE_PROJECT_ID = "smart-spark-382102"
GOOGLE_RECAPTCHA_ENTERPRISE_SITE_KEY = "6LfvLFssAAAAAKdjyYaM2N-oa4HA5PSEu5sE6K1P"

# LINE Bot
LINE_CHANNEL_SECRET = "bcb557fff2d2c7a6c930223e4a42b156"
LINE_CHANNEL_ACCESS_TOKEN = "sJBnvM/6WkWdmV6F4v/qBG+Z57Nq+frVGRhiKVs6/OXB3x/Q/3kGBHvaFbm30aFUD9hdWtJ3UmSDTns7bKX/54cKZJL1Nq+5IdJQv8o9HTNYKKoBUnbZLEVaTnZ3ttZso4pmKn6QbAU4oWEXQT2TtQdB04t89/1O/w1cDnyilFU="

# Meilisearch
MEILI_URL = os.getenv("MEILI_URL", "http://10.20.200.90:7700")

# 檔案上傳限制（10MB）
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes

