# Generated by Django 6.0 on 2026-01-22 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="form_template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="uuid",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="建立日期", verbose_name="建立日期"
                    ),
                ),
                (
                    "create_user",
                    models.CharField(
                        help_text="建立者", max_length=50, verbose_name="建立者"
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True, help_text="修改日期", verbose_name="修改日期"
                    ),
                ),
                (
                    "last_modified_user",
                    models.CharField(
                        help_text="修改者", max_length=50, verbose_name="修改者"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="模板名稱", max_length=100, verbose_name="模板名稱"
                    ),
                ),
                (
                    "json",
                    models.JSONField(help_text="模板架構", verbose_name="模板架構"),
                ),
            ],
            options={
                "verbose_name": "模板",
            },
        ),
    ]
