# Generated by Django 5.1.15 on 2026-01-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ithelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已完成', '已完成')], default='待處理', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('handler_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ithelps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IthelpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(max_length=255, upload_to='ithelp-files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ithelp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ithelps.ithelp')),
            ],
            options={
                'db_table': 'ithelp_files',
                'managed': True,
            },
        ),
    ]
