# Generated by Django 5.1.15 on 2026-01-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithelps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithelp',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刪除時間'),
        ),
        migrations.AddField(
            model_name='ithelp',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已刪除'),
        ),
    ]
